# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Programming for Biologists
tagline:          'A Jekyll theme'
description:      'Teaching biologists the tools they need to use computers to do cool science'
url:              http://www.programmingforbiologists.org/
baseurl:          /

author:
  name:           'Ethan White'
  url:            https://twitter.com/ethanwhite

github:
  repo:           https://github.com/ethanwhite/progbio/tree/gh-pages

gems:
  - jekyll-redirect-from